//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./statserver_types');
//HELPER FUNCTIONS AND STRUCTURES

StatServer_ping_args = function(args) {
};
StatServer_ping_args.prototype = {};
StatServer_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatServer_ping_args.prototype.write = function(output) {
  output.writeStructBegin('StatServer_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatServer_ping_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
StatServer_ping_result.prototype = {};
StatServer_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatServer_ping_result.prototype.write = function(output) {
  output.writeStructBegin('StatServer_ping_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatServer_calculateStat_args = function(args) {
  this.allNumbers = null;
  if (args) {
    if (args.allNumbers !== undefined) {
      this.allNumbers = args.allNumbers;
    }
  }
};
StatServer_calculateStat_args.prototype = {};
StatServer_calculateStat_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.allNumbers = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readI32();
          this.allNumbers.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatServer_calculateStat_args.prototype.write = function(output) {
  output.writeStructBegin('StatServer_calculateStat_args');
  if (this.allNumbers !== null && this.allNumbers !== undefined) {
    output.writeFieldBegin('allNumbers', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.I32, this.allNumbers.length);
    for (var iter7 in this.allNumbers)
    {
      if (this.allNumbers.hasOwnProperty(iter7))
      {
        iter7 = this.allNumbers[iter7];
        output.writeI32(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatServer_calculateStat_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
StatServer_calculateStat_result.prototype = {};
StatServer_calculateStat_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.StatStruct();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatServer_calculateStat_result.prototype.write = function(output) {
  output.writeStructBegin('StatServer_calculateStat_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatServer_generateNums_args = function(args) {
};
StatServer_generateNums_args.prototype = {};
StatServer_generateNums_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatServer_generateNums_args.prototype.write = function(output) {
  output.writeStructBegin('StatServer_generateNums_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatServer_generateNums_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
StatServer_generateNums_result.prototype = {};
StatServer_generateNums_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size8 = 0;
        var _rtmp312;
        this.success = [];
        var _etype11 = 0;
        _rtmp312 = input.readListBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = input.readI32();
          this.success.push(elem14);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StatServer_generateNums_result.prototype.write = function(output) {
  output.writeStructBegin('StatServer_generateNums_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.I32, this.success.length);
    for (var iter15 in this.success)
    {
      if (this.success.hasOwnProperty(iter15))
      {
        iter15 = this.success[iter15];
        output.writeI32(iter15);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StatServerClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
StatServerClient.prototype = {};
StatServerClient.prototype.ping = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_ping();
};

StatServerClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid);
  var args = new StatServer_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StatServerClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StatServer_ping_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ping failed: unknown result');
};
StatServerClient.prototype.calculateStat = function(allNumbers, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_calculateStat(allNumbers);
};

StatServerClient.prototype.send_calculateStat = function(allNumbers) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('calculateStat', Thrift.MessageType.CALL, this.seqid);
  var args = new StatServer_calculateStat_args();
  args.allNumbers = allNumbers;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StatServerClient.prototype.recv_calculateStat = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StatServer_calculateStat_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('calculateStat failed: unknown result');
};
StatServerClient.prototype.generateNums = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_generateNums();
};

StatServerClient.prototype.send_generateNums = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('generateNums', Thrift.MessageType.CALL, this.seqid);
  var args = new StatServer_generateNums_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StatServerClient.prototype.recv_generateNums = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StatServer_generateNums_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('generateNums failed: unknown result');
};
StatServerProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
StatServerProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

StatServerProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new StatServer_ping_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.ping(function (err, result) {
    var result = new StatServer_ping_result((err != null ? err : {success: result}));
    output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

StatServerProcessor.prototype.process_calculateStat = function(seqid, input, output) {
  var args = new StatServer_calculateStat_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.calculateStat(args.allNumbers, function (err, result) {
    var result = new StatServer_calculateStat_result((err != null ? err : {success: result}));
    output.writeMessageBegin("calculateStat", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

StatServerProcessor.prototype.process_generateNums = function(seqid, input, output) {
  var args = new StatServer_generateNums_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.generateNums(function (err, result) {
    var result = new StatServer_generateNums_result((err != null ? err : {success: result}));
    output.writeMessageBegin("generateNums", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

